services:
  clima:
    build: ./clima
    container_name: clima
    ports:
      - "5000:5000"

  temblor:
    build: ./temblor
    container_name: temblor
    ports:
      - "5001:5000"

  comportamiento:
    build: ./comportamiento
    container_name: comportamiento
    ports:
      - "5002:5000"
    depends_on:
      - clima
      - temblor
